
DROP USER SEMI;

--세미프로젝트용 테스트 DB계정 생성
CREATE USER SEMI IDENTIFIED BY Database4321;
GRANT CONNECT, 
	RESOURCE, 
	INSERT ANY TABLE,
	UPDATE ANY TABLE,
	DELETE ANY TABLE, 
	CREATE VIEW
	TO SEMI;
ALTER USER SEMI quota 50m ON USERS;

SELECT* FROM USER_TABLES;

DROP TABLE SEMI_ACCOUNTS;

