CREATE TABLE ACCOUNTDB (
	USER_ID VARCHAR2(30) PRIMARY KEY,--회원 ID(PK)
    PASSWORD VARCHAR2(30) CONSTRAINT PASSWORD_CK CHECK (LENGTH(PASSWORD) > 3),--패스워드 3자리 이상 제약조건
    IS_MANAGER CHAR(1) --관리자 유무
); --회원 DB

CREATE TABLE BOARDDB(
    BOARD_NUM    NUMBER PRIMARY KEY,  --게시판 번호(PK)
    BOARD_NAME VARCHAR2(30) --게시판 이름
); --게시판 DB

CREATE TABLE POSTDB(
    POST_NUM        NUMBER  PRIMARY KEY,--게시글 번호(PK)
    USER_ID       VARCHAR2(30) REFERENCES ACCOUNTDB(USER_ID), --쓴사람 ID(FK)
    POST_TITLE    VARCHAR2(30),--제목
    POST_CONTENT  VARCHAR(2000), --게시글 본문
    POST_DATE     DATE, --게시글 날짜
    BOARD_NUM     NUMBER  REFERENCES BOARDDB(BOARD_NUM) --게시판 번호(FK)
); --게시글 DB



CREATE TABLE COMMENTDB(
    COMMENT_NUM NUMBER PRIMARY KEY, --댓글 번호 (PK)
    POST_NUM NUMBER REFERENCES POSTDB(POST_NUM), --게시글 번호(FK)
    USER_ID VARCHAR2(30) REFERENCES ACCOUNTDB(USER_ID), --작성자 ID(FK)
    COMMENTS VARCHAR2(1000), --댓글 내용
    COMMENT_DATE DATE --댓글 쓴 날짜
); --댓글 DB



--0:FALSE(일반회원) 1:TRUE(관리자) 0이나 1만 지정 하게 체크
ALTER TABLE ACCOUNTDB ADD CHECK(IS_MANAGER IN ('0', '1'));

CREATE SEQUENCE COMMENTNUM_SEQ NOCACHE; --댓글 번호 자동 생성기

CREATE SEQUENCE BOARD_ORDER
    INCREMENT BY 10 
    START WITH 1; --카테고리 순서 정하는 시퀀스(1시작 10씩 번호증가)

CREATE SEQUENCE POSTNUM_SEQ NOCACHE; -- 게시글 번호 자동생성기

SELECT * FROM ACCOUNTDB;
INSERT INTO ACCOUNTDB VALUES("MANAGER", "1234", '1');



