CREATE TABLE USER1.ACCOUNTDB (
	USER_ID VARCHAR2(30) PRIMARY KEY,--회원 ID(PK)
    PASSWORD VARCHAR2(30) CONSTRAINT PASSWORD_CK CHECK (LENGTH(PASSWORD) > 3),--패스워드 3자리 이상 제약조건
    IS_MANAGER CHAR(1) --관리자 유무
); --회원 DB

CREATE TABLE USER1.BOARDDB(
    BOARD_NUM    NUMBER PRIMARY KEY,  --게시판 번호(PK)
    BOARD_NAME VARCHAR2(30) --게시판 이름
); --게시판 DB

CREATE TABLE USER1.POSTDB(
    POST_NUM        NUMBER  PRIMARY KEY,--게시글 번호(PK)
    USER_ID       VARCHAR2(30) REFERENCES ACCOUNTDB(USER_ID), --쓴사람 ID(FK)
    POST_TITLE    VARCHAR2(30),--제목
    POST_CONTENT  VARCHAR(2000), --게시글 본문
    POST_DATE     DATE, --게시글 날짜
    BOARD_NUM     NUMBER  REFERENCES BOARDDB(BOARD_NUM) --게시판 번호(FK)
); --게시글 DB



CREATE TABLE USER1.COMMENTDB(
    COMMENT_NUM NUMBER PRIMARY KEY, --댓글 번호 (PK)
    POST_NUM NUMBER REFERENCES USER1.POSTDB(POST_NUM), --게시글 번호(FK)
    USER_ID VARCHAR2(30) REFERENCES USER1.ACCOUNTDB(USER_ID), --작성자 ID(FK)
    COMMENTS VARCHAR2(1000), --댓글 내용
    COMMENT_DATE DATE --댓글 쓴 날짜
); --댓글 DB

INSERT INTO ACCOUNTDB VALUES('sungha', '123456', '0');
INSERT INTO BOARDDB VALUES('1', '성하게시판');
INSERT INTO POSTDB VALUES('1', 'sungha', '제목', '본문', TO_DATE('2021-10-30', 'YYYY-MM-DD'), '1');
INSERT INTO POSTDB VALUES('2', 'sungha', '가나다', '내가 뭐라고 했더라', TO_DATE('2021-11-30', 'YYYY-MM-DD'), '1');
INSERT INTO POSTDB VALUES('3', 'sungha', '마나아라하하', '내가...뭐라고.....했더라...?', TO_DATE('2021-12-01', 'YYYY-MM-DD'), '1');
INSERT INTO COMMENTDB VALUES(COMMENTNUM_SEQ.NEXTVAL, '1', 'sungha', 'Epik High is here', TO_DATE('2021-10-30', 'YYYY-MM-DD'));
INSERT INTO COMMENTDB VALUES(COMMENTNUM_SEQ.NEXTVAL, '1', 'sungha', 'Epik is here', TO_DATE('2021-11-20', 'YYYY-MM-DD'));
INSERT INTO COMMENTDB VALUES(COMMENTNUM_SEQ.NEXTVAL, '1', 'sungha', 'is here', TO_DATE('2021-11-30', 'YYYY-MM-DD'));
INSERT INTO COMMENTDB VALUES(COMMENTNUM_SEQ.NEXTVAL, '2', 'sungha', 'Epik High is here', TO_DATE('2021-10-30', 'YYYY-MM-DD'));

--0:FALSE(일반회원) 1:TRUE(관리자) 0이나 1만 지정 하게 체크
ALTER TABLE ACCOUNTDB ADD CHECK(IS_MANAGER IN ('0', '1'));

CREATE SEQUENCE COMMENTNUM_SEQ NOCACHE; --댓글 자동 생성기

CREATE SEQUENCE BOARD_ORDER
    INCREMENT BY 10
    START WITH 1 NOCACHE; --카테고리 순서 정하는 시퀀스


SELECT * FROM COMMENTDB; 
SELECT * FROM POSTDB;
SELECT * FROM COMMENTDB WHERE POST_NUM = '1' ORDER BY COMMENT_DATE;
SELECT * FROM COMMENTDB WHERE COMMENT_NUM = '11';
DELETE FROM COMMENTDB WHERE COMMENT_NUM = '9';
UPDATE COMMENTDB SET COMMENTS = 'is here mymy', COMMENT_DATE = TO_DATE('2021-12-01', 'YYYY-MM-DD') WHERE COMMENT_NUM = '6';
DELETE FROM COMMENTDB WHERE POST_NUM = '2';
